---
title: "p8105_hw5_bsr2136"
author: "Barik Rajpal"
date: "11/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 0

```{r p0, warning=FALSE}
dir.create("files_for_hw5")
```

## Problem 1

```{r p1}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

### Function to remove missing values

```{r p1.1}
remove_missing <- function(x) {
  
  if (is.numeric(x)) {
      for (i in 1:length(x)) {
          if (is.na(x[i])) {
              x[i] = mean(x,na.rm=T)
          }
      }
  }
  else if (is.character(x)) {
          for (i in 1:length(x)) {
              if (is.na(x[i])) {
                  x[i] = "virginica"
              }
          }
  }
  else stop("Not numeric or character")
  x
}
```

### Applying the function to iris_with_missing df

```{r p1.2}
map(iris_with_missing,remove_missing)
```

## Problem 2

```{r p2, message = F}
names_df <- tibble(
                short_file = list.files("./files_for_hw5"),
                filenames = list.files("./files_for_hw5") %>%
                str_c("./files_for_hw5/",.)
            )

names_df <- names_df %>%
  mutate(list = map(pull(names_df,filenames), read_csv)) %>%
  unnest(list) %>%
  mutate(arm = ifelse(str_detect(short_file,"con"),"Control","Experimental"),
         subject_id = as.numeric(str_match(short_file,"[0-9]+"))
         ) %>%
  select(arm,subject_id,everything(),-short_file,-filenames) %>%
  pivot_longer(cols = week_1:week_8,
              names_to = "week",
              values_to = "observations") %>%
  mutate(week = as.numeric(str_match(week,"[0-9]+"))
           )

names_df %>%
  ggplot(aes(x=week,y=observations,color=as.factor(subject_id))) + 
  geom_line() +
  facet_grid(.~arm) + labs(color = "subject_id")

```

The experimental subject observation values increase fairly significantly over time. The control subject observation values fluctuate over time, but don't noticeably increase or decrease over time.

## Problem 3

```{r p3}

```

